### ISSUE TITLE
Информация о теле запроса событий не соответствует действительности

### ISSUE THREAD

**Issue by 7-zete-7** [bitrix-tools/b24-rest-docs#55]
Ранее (до 26.11.2024) тело событий выглядело следующим образом:
```yaml
event: ONEXTERNALCALLSTART
data:
  PHONE_NUMBER: redacted
  PHONE_NUMBER_INTERNATIONAL: redacted
  EXTENSION: redacted
  USER_ID: redacted
  CALL_LIST_ID: redacted
  LINE_NUMBER: redacted
  IS_MOBILE: redacted
  CALL_ID: redacted
  CRM_ENTITY_TYPE: redacted
  CRM_ENTITY_ID: redacted
ts: "1732512039"
auth:
  access_token: redacted
  expires: redacted
  expires_in: redacted
  scope: redacted
  domain: example.com
  server_endpoint: https://oauth.bitrix.info/rest/
  status: redacted
  client_endpoint: https://example.com/rest/
  member_id: redacted
  user_id: redacted
  application_token: redacted
```

Сейчас (27.11.2024) тело событий стало таким:
```yaml
event: ONEXTERNALCALLSTART
event_handler_id: redacted
data:
  PHONE_NUMBER: redacted
  PHONE_NUMBER_INTERNATIONAL: redacted
  EXTENSION: redacted
  USER_ID: redacted
  CALL_LIST_ID: redacted
  LINE_NUMBER: redacted
  IS_MOBILE: redacted
  CALL_ID: redacted
  CRM_ENTITY_TYPE: redacted
  CRM_ENTITY_ID: redacted
ts: "1732698354"
auth:
  access_token: redacted
  expires: redacted
  expires_in: redacted
  scope: redacted
  domain: example.com
  status: redacted
  client_endpoint: https://example.com/rest/
  member_id: redacted
  user_id: redacted
  application_token: redacted
```

Наблюдается изменение (не считая параметра `ts`):
```diff
@@ -1,2 +1,3 @@
 event: ONEXTERNALCALLSTART
+event_handler_id: redacted
 data:

@@ -18,12 +18,11 @@
 auth:
   access_token: redacted
   expires: redacted
   expires_in: redacted
   scope: redacted
   domain: example.com
-  server_endpoint: https://oauth.bitrix.info/rest/
   status: redacted
   client_endpoint: https://example.com/rest/
   member_id: redacted
   user_id: redacted
   application_token: redacted
```

В документации не описано это изменение. Описывается только предыдущий набор данных.
